# file: postgresql/tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Make sure the PostgreSQL users are present
  community.postgresql.postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
    login_unix_socket: "{{postgresql_unix_socket_directories[0]}}"
    db: postgres
  no_log: true
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  loop: "{{ postgresql_users | default([]) }}"
  when: (postgresql_users | default([])) | length > 0
  loop_control:
    label: "{{ item.name }}"
